name: Type Check
on:
  workflow_call:

jobs:
  typecheck:
    name: Run type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dev deps
        run: uv sync --group dev

      - name: Type check
        run: uv run pyright

      - name: Type check
        run: uv run mypy .

